<a href="https://colab.research.google.com/github/pseeej/MachineLearning_DCLAB/blob/master/My%20First%20ML%2CDL/4.9.4%20Softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical
from keras.datasets import mnist

In [ ]:
# 데이터 받아오기

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
# 데이터 형태 확인

print("train data (count, row, column) : " + str(X_train.shape) )
print("test data  (count, row, column) : " + str(X_test.shape) )

train data (count, row, column) : (60000, 28, 28)
test data  (count, row, column) : (10000, 28, 28)


In [ ]:
# 학습 데이터 하나 샘플로 출력

print(X_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [ ]:
# 데이터 정규화

X_train = X_train.astype('float32') 
X_test = X_test.astype('float32') 
X_train /= 255 
X_test /= 255

In [ ]:
# 정규화된 데이터 확인

print(X_train[0])

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

In [ ]:
# 타겟 데이터 형태 확인

print("train target (count) : " + str(y_train.shape) )
print("test target  (count) : " + str(y_test.shape) )

train target (count) : (60000,)
test target  (count) : (10000,)


In [ ]:
# y_train과 y_test에서 샘플로 숫자 출력

print("sample from train : " + str(y_train[0]) )
print("sample from test : " + str(y_test[0]) )

sample from train : 5
sample from test : 7


In [ ]:
# 배열 크기 변경. 데이터 단순화

input_dim = 784 #28*28 
X_train = X_train.reshape(60000, input_dim) 
X_test = X_test.reshape(10000, input_dim)

In [ ]:
# 데이터 배열 크기 확인

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [ ]:
# 소프트맥스
# one hot encoding으로 변환

num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [ ]:
print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# 소프트맥스 구현. 784개 입력 받아 시그모이드 값 출력하는 모델 구현

model = Sequential() 
model.add(Dense(input_dim=input_dim, units = 10, activation='softmax'))

In [ ]:
# 모델 학습

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy']) 
model.fit(X_train, y_train, batch_size=2048, epochs=100, verbose=0)

In [ ]:
# 테스트 진행하여 정확도 측정

score = model.evaluate(X_test, y_test) 
print('Test accuracy:', score[1])

313/313 [==============================] - 0s 976us/step - loss: 0.4208 - accuracy: 0.8895
Test accuracy: 0.8895000219345093


In [ ]:
# 모델 요약

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 회귀계수의 개수와 편향의 개수 확인

model.layers[0].weights

[<tf.Variable 'dense/kernel:0' shape=(784, 10) dtype=float32, numpy=
 array([[-0.04757889, -0.05389724, -0.00420328, ..., -0.07271893,
         -0.07686607, -0.05345302],
        [ 0.05881979, -0.05166555,  0.03189488, ..., -0.06565155,
         -0.06024648, -0.04047369],
        [-0.01370355,  0.05065276,  0.05637128, ..., -0.03592792,
          0.0205285 , -0.01101959],
        ...,
        [-0.07264237, -0.00956739,  0.04411343, ..., -0.0170907 ,
         -0.01130121, -0.03287364],
        [-0.01504485,  0.05900707,  0.08441249, ..., -0.07233584,
          0.08198392, -0.06153973],
        [ 0.05881005,  0.07075017,  0.02965163, ..., -0.08457109,
          0.04706477, -0.07046182]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=
 array([-0.07862854,  0.16585764, -0.04480625, -0.05429575,  0.03808127,
         0.15825438, -0.01770636,  0.11100926, -0.2459072 , -0.03185946],
       dtype=float32)>]